// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL?.startsWith("https://") || !SUPABASE_PUBLISHABLE_KEY) {
  console.error(
    "[Supabase] VITE_SUPABASE_URL et VITE_SUPABASE_PUBLISHABLE_KEY doivent être définis dans .env (voir .env.example)"
  );
}

export const supabase = createClient<Database>(
  SUPABASE_URL ?? "",
  SUPABASE_PUBLISHABLE_KEY ?? "",
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      flowType: "pkce",
      detectSessionInUrl: true,
    },
    global: {
      // Ignorer les erreurs de cookies Cloudflare (bénignes)
      fetch: (url, options = {}) => {
        return fetch(url, {
          ...options,
          credentials: 'omit', // Ne pas envoyer de cookies tiers
        }).catch((error) => {
          // Ignorer les erreurs de cookies Cloudflare
          if (error.message?.includes('cookie') || error.message?.includes('__cf_bm')) {
            console.warn('[Supabase] Cookie warning ignoré:', error.message);
            // Réessayer sans credentials si nécessaire
            return fetch(url, options);
          }
          throw error;
        });
      },
    },
  }
);
